server:
  port: 9003
spring:
  jpa:
    show-sql: true
  elasticsearch:
    uris: 120.53.222.40:9200
    username: elastic
    password: 2ii3lABYkZCCrjkSBKAs

com:
  madao:
    aopPointcutExpression: execution (* com.madao.article.service..*.*(..))

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE

springdoc:
  packages-to-scan:
    - com.madao.article.controller
    - com.madao.model
  paths-to-match:
    - /api/**
    - /**
