server:
  port: 9003

com:
  madao:
    aopPointcutExpression: execution (* com.madao.article.service..*.*(..))

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE