server:
  port: 9003
spring:
  jpa:
    show-sql: true

#elasticsearch:
#  host: 82.156.205.178
#  port: 9200
#  username:
#  password:
com:
  madao:
    aopPointcutExpression: execution (* com.madao.article.service..*.*(..))

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE

springdoc:
  packages-to-scan:
    - com.madao.article.controller
    - com.madao.model
  paths-to-match:
    - /api/**
    - /**

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: TRACE