server:
  port: 8090
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: yourClientId
            clientSecret: yourClientSecret
          qq:
            clientId: yourClientId
            clientSecret: yourClientSecret
            authorization-grant-type: code
        provider:
          qq:
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys

encrypt:
  key-store:
    location: classpath:madao.keystore
    secret: madaoo.com
    alias: madaoo.com
    password: madaoo.com