server:
  port: 8090
spring:
  application:
    name: authentication-server


encrypt:
  key-store:
    location: classpath:madao.keystore
    secret: madaoo.com
    alias: madaoo.com
    password: madaoo.com