server:
  port: 9009
spring:
  application:
    name: server-config #指定服务名
  cloud:
    compatibility-verifier:
      enabled: false # 关闭Spring Cloud Sleuth 与Spring Cloud 版本不适配问题，暂时关闭校验，延迟解决

# 消息总线BUS自动刷新配置文件
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
  security:
    enabled: false # 刷新时，关闭安全验证