server:
  port: 9007
spring:
  application:
    name: service-user
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

com:
  madao:
    aopPointcutExpression: execution (* com.madao.user..*.*(..))

